[build-system]
requires = ["setuptools"]

[project]
name = "dqm"
authors = [{name = "Zander Teller", email = "zander.teller@gmail.com"}]
description = "Dynamic Quantum Mapping"
version = "0.1.0"

[tool.setuptools]
packages = ["dqm"]
